package:
  name: mopac7
  version: "7.00"

build:
  number: 0

source:
  url: http://openmopac.net/Downloads/Mopac7executable.zip
  sha256: bab7c28afffb8c8d9740f9364fb28b32802c4b207c996371dbe4699ec6f98f04

about:
  home: http://openmopac.net/
  license: Public Domain
  summary: "a semiempirical quantum chemistry program based on Dewar and Thiel's NDDO approximation."
