package:
  name: coveralls
  version: "1.3.0"

build:
  number: 0

source:
  git_url: https://github.com/coveralls-clients/coveralls-python.git
  git_rev: v1.3.0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/coveralls-clients/coveralls-python
  license: MIT License
  summary: 'Show coverage stats online via coveralls.io'

test:
  imports:
    - coveralls
