package:
  name: progressbar2
  version: "3.6.1"

source:
  git_url: https://github.com/WoLpH/python-progressbar.git
  git_rev: v3.6.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/WoLpH/python-progressbar
  license: BSD License
  summary: 'A Python Progressbar library to provide visual (yet text based) progress to\nlong running operations.'
