package:
  name: mopac7
  version: "7.01"

build:
  number: 0

source:
  url: http://bioinformatics.org/ghemical/download/current/mopac7-1.15.tar.gz
  sha256: 6d7ac5d78522db70f7794fd816cea32829cfa9e93774202fe80ba5a54375fbaa

requirements:
  build:
    - make
    - libtool
    - automake
    - autoconf

about:
  home: http://openmopac.net/
  license: Public Domain
  summary: "a semiempirical quantum chemistry program based on Dewar and Thiel's NDDO approximation."
