package: tqdm
user: mordred-descriptor

platform: 
 - linux-64

engine:
 - python=2.7
 - python=3.4
 - python=3.5

script:
  - conda build .

after_success:
  - if [[ ! -d "$CONDA_BUILD_DIR" ]]; then
      CONDA_BUILD_DIR=/opt/miniconda/conda-bld/linux-64;
    fi
  - conda convert $CONDA_BUILD_DIR/*.tar.bz2 -p osx-64 -p win-32 -p win-64

build_targets:
  - conda
  - ./osx-64/*.tar.bz2
  - ./win-64/*.tar.bz2
  - ./win-32/*.tar.bz2
