package:
  name: tqdm
  version: "3.7.1"

build:
  number: 1
  script:
    - git cherry-pick 23c596fb331478cbc15d1854b61a3e63284da3a5
    - $PYTHON setup.py install

source:
  git_url: https://github.com/tqdm/tqdm.git
  git_rev: v3.7.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/tqdm/tqdm#license
  license: MIT License
  summary: 'A fast, extensible progress bar for Python'

test:
  imports:
    - tqdm
