package:
  name: tqdm
  version: "4.0.0"

build:
  number: 0
  script:
    - $PYTHON setup.py install

source:
  git_url: https://github.com/tqdm/tqdm.git
  git_rev: v4.0.0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/tqdm/tqdm#license
  license: MIT License
  summary: 'A fast, extensible progress bar for Python'

test:
  imports:
    - tqdm
